# -*- coding: utf-8 -*-
"""Orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1px2TNsUjRE_ApWj-F81ygQmir0neq-9r

Example of addition
"""

A=2
B=3
C=2+3
print(C)

"""Example of string"""

Greetings= "Advice na, pror"
print (Greetings)