# -*- coding: utf-8 -*-
"""Weekend_assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17aj_n26SXd744wG1bPg2AwmqAfK-zh30

Part 1: Understanding print()-Variable vs. Quoted Text
"""

Liberia = 1847
print(Liberia)
print("Liberia")

"""print(Liberia) prints the value of the variable Liberia, which is 1847 because we set Liberia=1847"""

country = "Liberia"
print(country, "became independent in", 1847)

print('The year is "1847"')

"""Part 2: Creating Variables with Different Data Types"""

market_name = "Gobachop Market"
total_market_table = 150
price_per_bag = 3200.50
is_market_open = True

print("Market name:", market_name)
print("Total market tables:",total_market_table)
print("Price per bag:",price_per_bag)
print("Is market open:", is_market_open)

#Bonus: print types
print(type(market_name))
print(type(total_market_table))
print(type(price_per_bag))
print(type(is_market_open))

current_price = 2550.75
quantity = 10
total_cost = current_price * quantity
print("Total cost:", total_cost, "LRD")

has_scarcity = False
is_rainy = True

print("Scarcity today:",has_scarcity)
print("Rainy today:",is_rainy)

"""Part 3: Arithmetic with Variables_Market Scenarios"""

price_per_bag = 800
quantity = 25
total_revenue = price_per_bag * quantity
print("Total revenue:", total_revenue, "LRD")

today_price = 3200
increase = 150
tomorrow_price = today_price + increase
print("Tomorrow's price:",tomorrow_price, "LRD")

cost = 1800
num_traders = 3
cost_per_trader = cost / num_traders
print("Cost per trader:",cost_per_trader, "LRD")

original_price = 2500
discount_rate = 0.10
discount_amount = original_price * discount_rate
final_price = original_price - discount_amount

print("Discount amount:", discount_amount, "LRD")
print("Final price:",final_price, "LRD")

"""Part 4: Mixing Variables and Print"""

item = "cassava"
price = 800
print(item)
print("item")
print(price)
print("price")

product = "pepper"
cost = 150.5
print("One bag of",product,"costs",cost,"LRD")

rice_total = 0 # Placeholder: Replace with actual calculation for rice
sugar_total = 0 # Placeholder: Replace with actual calculation for sugar
oil_total = 0 # Placeholder: Replace with actual calculation for oil

#do the same for sugar and oil
total_revenue = rice_total + sugar_total + oil_total
print("Total revenue:", total_revenue, "LRD")